### ISSUE TITLE
can you consider this in running in a separate thread

### ISSUE THREAD

**Issue by FuncGuy** [HeshanSudarshana/distributed-content-searching#1]
https://github.com/HeshanSudarshana/distributed-content-searching/blob/bb9199ef1317920386ea9b55f742b903d914f82f/src/node/Node.java#L125

**Comment by oshadaamila** [comment]
yes, it runs in a seperate thread, what  do you mean by consider??

**Comment by FuncGuy** [comment]
Ok. i didn't see any thread creation mechanics so i thought it was blocking call..
